### ISSUE TITLE
Семинар 7-8

### ISSUE THREAD

**Issue by denisenes** [bd986650/23217_belovdanil#6]
> -- эту функцию взял с гпт, потому что мое решение не работало нормально(тогда и последущие таски бы слетели изза этой фукнции)
-- в гугле и на гитхабе 0 инфы полезной было про создание матриц на хаскеле (((

Прошу обратить внимание на сигнатуру функции. Она очень похожа на сигнатуру одной из функций для создания массивов. Т.к. матрица -- это всего лишь обертка над массивом, кажется закономерным ее использовать

**Comment by bd986650** [comment]
makeMatrix size list = array ((1, 1),size) list 
Так ?

**Comment by denisenes** [comment]
> Так ?

Нет, это ведь даже не компилируется. Нам надо сконструировать тип матрицы, для этого можно использовать конструктор данных Matrix
```haskell
makeMatrix size list = Matrix (array ...)
```

Ну и надо обратить внимание на размеры матриц: `m1 = makeMatrix (3, 3) example1` принимает размер `(3,3)`, а индексация в `example1` происходит в отрезке [0..2]. В makeMatrix значит в функцию `array` принимаемый size в исходном виде передавать нельзя

**Comment by denisenes** [comment]
Ладно, я пока не буду проверять, много заданий не сделано. Пока оценку не ставлю, даю еще время на доделки

**Comment by bd986650** [comment]
мб просто оценку ? я не смогу сделать оставшиеся задачи

**Comment by denisenes** [comment]
Как знаешь
За то что есть могу поставить не больше 3.2
